### ISSUE TITLE
Can't choose which course to upload my work

### ISSUE THREAD

**Issue by DavidLSC** [SBUtltmedia/Marginalia#47]
The course menu is added to the add lit page. Need new API that also take the course value.

**Comment by shortland** [comment]
yeah... let me handle this one. the front-end that deals with courses is in modules... which is heavily separated from other code without some heavy refactoring or a dirty hackaround.

**Comment by DavidLSC** [comment]
I already made a menu for users to select a course at the add literature page. If you can make an API that also include the course name for upload work it should solve the problem.

**Comment by shortland** [comment]
oh nice, it'll be easier than i thought then

**Comment by shortland** [comment]
implemented feature.
