### ISSUE TITLE
Problems for setting work to private

### ISSUE THREAD

**Issue by DavidLSC** [SBUtltmedia/Marginalia#48]
I tried to set the work to private. However the API endpoint "is_public" keep returning the work is public. The work also shows up when I logged in as another user.

**Comment by shortland** [comment]
this is def a problem with the courses thing i implemented... i'll work on it later tonight or tomorrow. def before we see Brandi on friday.

@DavidLSC ty, keep making issues for other problems if u see them

**Comment by shortland** [comment]
@DavidLSC we have a "privacy" and "public" field in a work's `permissions.json` file...

Do you remember the difference between the two? B/c I can't recall...
I think there's some overlap in the backend code that sometimes sets one of those and gets the other by accident or something?

**Comment by shortland** [comment]
...
So, `public` is used in `comment.json` files.
But, `privacy` is used for Works/ `permissions.json` files...
But sometimes we are setting/getting `public` in the permissions.json files... 

I'll work on getting this working properly rn.

**Comment by shortland** [comment]
In additional, some functions are setting privacy as a string when it should be a bool value in `permissions.json` file.

**Comment by shortland** [comment]
fixed
